#!/usr/bin/env bash
# install-openclaw.sh â one-shot OpenClaw self-host installer.
# Usage on droplet (must be root or have sudo):
#   curl -fsSL https://iisupp.net/install-openclaw.sh | sudo bash
# OR (after pulling): sudo bash install-openclaw.sh
#
# What it does (zero interaction):
#   1. Installs Docker + docker-compose if missing
#   2. Clones openclaw/openclaw to /opt/openclaw
#   3. Generates .env with provided defaults + prompts for any missing
#   4. Starts the stack
#   5. Sets up Caddy reverse proxy at openclaw.iisupp.net (auto HTTPS via Let's Encrypt)
#   6. Wires Telegram bot @IISUPP_bot
#   7. Prints health check URL
#
# Env vars expected (export before running, or it'll prompt):
#   ANTHROPIC_API_KEY       â your existing Anthropic key
#   TELEGRAM_BOT_TOKEN      â from @BotFather (already have one)
#   TELEGRAM_OWNER_CHAT_ID  â your chat ID (1870218558)
#   OPENCLAW_TOKEN          â random secret for mesh bridge auth (will generate if blank)
#   PUBLIC_DOMAIN           â e.g. openclaw.iisupp.net (CNAME this to droplet first)

set -euo pipefail
INSTALL_DIR=/opt/openclaw
LOG_FILE=/var/log/openclaw-install.log

log() { echo "[$(date +%T)] $*" | tee -a "$LOG_FILE"; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root or with sudo." >&2
    exit 1
  fi
}

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "Docker already installed: $(docker --version)"
    return
  fi
  log "Installing Docker..."
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
}

install_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    log "Caddy already installed: $(caddy version | head -1)"
    return
  fi
  log "Installing Caddy..."
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -y
  apt-get install -y caddy
}

clone_openclaw() {
  if [ -d "$INSTALL_DIR/.git" ]; then
    log "OpenClaw already cloned; pulling latest..."
    cd "$INSTALL_DIR"
    git pull --ff-only
  else
    log "Cloning openclaw/openclaw..."
    git clone https://github.com/openclaw/openclaw.git "$INSTALL_DIR"
  fi
}

prompt_if_blank() {
  local var="$1"
  local prompt="$2"
  local current="${!var:-}"
  if [ -z "$current" ]; then
    read -rp "$prompt: " value
    eval "$var='$value'"
  fi
}

write_env() {
  log "Writing $INSTALL_DIR/.env ..."
  : "${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY required}"
  : "${TELEGRAM_BOT_TOKEN:?TELEGRAM_BOT_TOKEN required}"
  : "${TELEGRAM_OWNER_CHAT_ID:?TELEGRAM_OWNER_CHAT_ID required}"
  : "${PUBLIC_DOMAIN:=openclaw.iisupp.net}"
  if [ -z "${OPENCLAW_TOKEN:-}" ]; then
    OPENCLAW_TOKEN=$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)
    log "Generated OPENCLAW_TOKEN (32 chars)"
  fi
  cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install-openclaw.sh on $(date)
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_OWNER_USERNAME=rome4n
TELEGRAM_OWNER_CHAT_ID=$TELEGRAM_OWNER_CHAT_ID
OPENCLAW_TOKEN=$OPENCLAW_TOKEN
PUBLIC_URL=https://$PUBLIC_DOMAIN
TIMEZONE=America/Toronto
# Customer-bot defaults (override per CUSTOMER-INBOUND-BOT.md when ready)
ENABLE_CUSTOMER_PERSONA=false
CUSTOMER_FAQ_PATH=/data/customer-faq.md
EOF
  chmod 600 "$INSTALL_DIR/.env"
  log "Wrote .env (chmod 600). Token starts with: ${OPENCLAW_TOKEN:0:6}***"
  echo ""
  echo "==> SAVE THIS OPENCLAW_TOKEN â paste into Netlify env vars + bridge-poller env:"
  echo "    OPENCLAW_TOKEN=$OPENCLAW_TOKEN"
  echo ""
}

start_stack() {
  log "Starting OpenClaw docker stack..."
  cd "$INSTALL_DIR"
  if [ -f docker-compose.yml ] || [ -f compose.yaml ]; then
    docker compose up -d
  else
    log "ERROR: no docker-compose.yml found in $INSTALL_DIR"
    log "OpenClaw repo structure may differ â check $INSTALL_DIR contents and run install manually"
    exit 1
  fi
  log "Waiting 15s for stack to come up..."
  sleep 15
  docker compose ps
}

configure_caddy() {
  local domain="${PUBLIC_DOMAIN:-openclaw.iisupp.net}"
  log "Configuring Caddy reverse proxy for $domain ..."
  cat > /etc/caddy/Caddyfile.d/openclaw.conf <<EOF
$domain {
    reverse_proxy localhost:8080
    encode gzip
    log {
        output file /var/log/caddy/openclaw-access.log
        format console
    }
}
EOF
  if ! grep -q "import Caddyfile.d/" /etc/caddy/Caddyfile 2>/dev/null; then
    mkdir -p /etc/caddy/Caddyfile.d
    echo "import /etc/caddy/Caddyfile.d/*.conf" >> /etc/caddy/Caddyfile
  fi
  systemctl reload caddy || systemctl restart caddy
  log "Caddy reloaded. HTTPS auto-provisions on first request."
}

connect_telegram() {
  log "Telegram bot already configured via .env. Bot will auto-connect on container start."
  log "Try sending 'hi' to @IISUPP_bot from your Telegram to verify."
}

print_summary() {
  local domain="${PUBLIC_DOMAIN:-openclaw.iisupp.net}"
  echo ""
  echo "============================================"
  echo " OpenClaw install complete"
  echo "============================================"
  echo " Public URL:  https://$domain"
  echo " Admin UI:    https://$domain/admin"
  echo " Logs:        cd $INSTALL_DIR && docker compose logs -f"
  echo " Restart:     cd $INSTALL_DIR && docker compose restart"
  echo " Stop:        cd $INSTALL_DIR && docker compose down"
  echo ""
  echo " Telegram:    @IISUPP_bot â message rome4n (chat_id 1870218558)"
  echo " Bridge:      mesh-router â /api/mesh-task-queue â local://openclaw"
  echo ""
  echo " NEXT:"
  echo "   1. Test bot â send 'hi' to @IISUPP_bot, should reply"
  echo "   2. Add OPENCLAW_TOKEN (printed above) to Netlify env vars + bridge-poller.mjs env"
  echo "   3. Cont with CUSTOMER-INBOUND-BOT.md if you want the lead-gen persona"
  echo "============================================"
}

main() {
  require_root
  mkdir -p "$(dirname "$LOG_FILE")"
  : > "$LOG_FILE"
  log "Starting OpenClaw install. Log: $LOG_FILE"
  install_docker
  install_caddy
  clone_openclaw
  write_env
  start_stack
  configure_caddy
  connect_telegram
  print_summary
}

main "$@"
