const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const wrapper=fs.readFileSync(path.join(__dirname,'../assets/aria-live-voice.js'),'utf8');
function setup(){let options,stops=0,creates=0;const states=[];const errors=[];const ctx={window:{},document:{readyState:'loading',addEventListener(){},createElement(){return{style:{}}},body:{appendChild(){}}},URL,Promise,fetch:async()=>({ok:true,json:async()=>({url:'wss://example.test/api/live'})})};ctx.window.AriaLive={create(o){options=o;creates++;return{async start(){},stop(){stops++;options.onEvent({type:'app.stopping'})}}}};vm.runInNewContext(wrapper,ctx);const call=ctx.window.AriaLiveCall('axis',{onState:s=>states.push(s),onError:m=>errors.push(m)});return{call,states,errors,event:e=>options.onEvent(e),get stops(){return stops},get creates(){return creates}}}
test('readiness requires connected media, not an SDP answer',async()=>{const x=setup();await x.call.toggle();x.event({type:'gateway.session.created'});assert.deepEqual(x.states,['connecting']);x.event({type:'app.connected'});assert.equal(x.states.at(-1),'live')});
test('nonterminal feedback does not orphan live audio',async()=>{const x=setup();await x.call.toggle();x.event({type:'error',error:{message:'Command rejected'}});assert.equal(x.call.active,true);assert.equal(x.errors[0],'Command rejected');await x.call.toggle();assert.equal(x.stops,1);assert.equal(x.creates,1)});
test('Stop drains before allowing another receiver',async()=>{const x=setup();await x.call.toggle();await x.call.toggle();assert.equal(x.call.active,true);assert.equal(x.states.at(-1),'stopping');x.event({type:'app.closed'});assert.equal(x.call.active,false);await x.call.toggle();assert.equal(x.creates,2)});
const app=fs.readFileSync(path.join(__dirname,'../assets/axis-app.js'),'utf8');
test('authenticated main mic starts Live and no legacy recognizer',()=>{const fn=app.slice(app.indexOf('function axisMicToggle('),app.indexOf('// Which surface'));let starts=0;vm.runInNewContext(fn+'; axisMicToggle()',{state:{token:'staff'},window:{axisLiveToggle(){starts++}},axisWakePause(){},axisRec:null,axisSend(){},ariaStop(){},axisSyncWakeBtn(){}});assert.equal(starts,1)});
test('legacy replies cannot interrupt the live receiver',()=>{const fn=app.slice(app.indexOf('function axisSpeak(text)'),app.indexOf('function axisSpeakBrowser(text)'));let reads=0;vm.runInNewContext(fn+'; result=axisSpeak("reply")',{window:{axisLiveActive:true},axisSpeakBrowser(){reads++;}});assert.equal(reads,0)});
