// u1-outbound-truth.test.mjs — RUN-U U1/U2 exit criteria, test-locked.
//
// The failure this suite exists to make impossible: RUN 110-129 published `asksSent: 0` during a
// 41-send week because the counters read an internal log that outbound was never written into.
// These tests prove (a) the counter reads the mail record and nothing else, (b) `0`, `never` and
// `unverified` stay three distinct facts, (c) software progress cannot move a single number, and
// (d) the reconciliation names an understated counter as a Rule 14 failure.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  buildOutboundTruth, normalizeEvent, reconcileWithClaimed, outboundFacts, outboundMarkdown,
  OUTBOUND_TRUTH_SCHEMA, NEVER, UNVERIFIED, EVENT_KINDS,
  SENDS, HAS_TRANSPORT, PERSISTS, READS_IDENTITY,
} from "../src/shared/outbound-truth.mjs";

const NOW = Date.parse("2026-07-28T23:00:00Z");
const SRC = "src/shared/outbound-truth.mjs";
const RECORD = "../../senior-director-state/outbound/outbound-record-2026-07-28.json";

const realRecord = () =>
  JSON.parse(readFileSync(new URL(RECORD, import.meta.url), "utf8"));

test("U1: with NO mail source, every counter reads `unverified` - never 0", () => {
  const t = buildOutboundTruth({ events: [] }, { now: NOW });
  assert.equal(t.schema, OUTBOUND_TRUTH_SCHEMA);
  assert.equal(t.sourced, false);
  const f = outboundFacts(t);
  for (const k of ["emailsSent", "personalReplies", "meetingsBooked", "conversationsHeld", "revenue"]) {
    assert.equal(f[k], UNVERIFIED, `${k} must be unverified, not 0, when no mail was read`);
    assert.notEqual(f[k], 0);
    assert.notEqual(f[k], NEVER);
  }
  assert.match(outboundMarkdown(t), /unverified/);
});

test("U1: `0`, `never` and `unverified` are three distinct renderings", () => {
  const sourced = buildOutboundTruth(
    { source: "mail", events: [{ kind: "sent", at: "2026-07-28T10:00:00Z", handle: "OB-S001" }] },
    { now: NOW },
  );
  const f = outboundFacts(sourced);
  assert.equal(f.emailsSent, 1);                 // read the mail, found one
  assert.equal(f.meetingsBooked, NEVER);         // read the mail, it has never happened
  const unsourced = outboundFacts(buildOutboundTruth({ events: [] }, { now: NOW }));
  assert.equal(unsourced.meetingsBooked, UNVERIFIED); // did not read the mail at all
  assert.notEqual(f.meetingsBooked, unsourced.meetingsBooked);
  assert.notEqual(f.meetingsBooked, 0);
});

test("U1: the real recorded mail set reproduces the first-hand numbers", () => {
  const t = buildOutboundTruth(realRecord(), { now: NOW });
  const f = outboundFacts(t);
  assert.equal(t.sourced, true);
  assert.equal(f.emailsSent, 41, "41 outreach emails in the 3-day window, read first-hand");
  assert.equal(f.personalReplies, 0, "one personal reply exists, but it is outside the 3-day window");
  assert.equal(t.counters.personalReplies.everTotal, 1, "and it is still on the record as ever-happened");
  assert.equal(t.counters.personalReplies.state, "counted");
  assert.equal(t.counters.undeliverable.everTotal, 4);
  assert.equal(t.counters.autoReplies.everTotal, 11);
  assert.equal(f.meetingsBooked, NEVER);
  assert.equal(f.conversationsHeld, NEVER);
  assert.equal(f.revenue, NEVER);
  assert.equal(f.daysSinceMeetingBooked, NEVER);
  assert.equal(f.warmRedirects, 7, "seven autoresponders handed back an alternate route (five named a colleague or successor, two gave a direct phone) - free, warm, and generated by the sending itself");
  assert.equal(f.returnDatesPending, 6);
});

test("U1: an out-of-office is never counted as a reply, a meeting or a conversation", () => {
  const t = buildOutboundTruth({
    source: "mail",
    events: [
      { kind: "sent", at: "2026-07-28T10:00:00Z", handle: "OB-S001" },
      { kind: "auto-reply", at: "2026-07-28T10:05:00Z", handle: "OB-A001", redirectOffered: true },
    ],
  }, { now: NOW });
  const f = outboundFacts(t);
  assert.equal(f.autoReplies, 1);
  assert.equal(f.personalReplies, NEVER);
  assert.equal(f.meetingsBooked, NEVER);
  assert.equal(f.conversationsHeld, NEVER);
});

test("U1: a bounce is subtracted from delivered - a send that did not land is not a send that landed", () => {
  const t = buildOutboundTruth({
    source: "mail",
    events: [
      { kind: "sent", at: "2026-07-28T10:00:00Z", handle: "OB-S001" },
      { kind: "sent", at: "2026-07-28T10:01:00Z", handle: "OB-S002" },
      { kind: "undeliverable", at: "2026-07-28T10:02:00Z", handle: "OB-S002", reason: "address not found" },
    ],
  }, { now: NOW });
  assert.equal(outboundFacts(t).emailsSent, 2);
  assert.equal(t.delivered, 1);
});

test("U1: identity can never enter the path (vault Rule 11)", () => {
  const bad = normalizeEvent({ kind: "sent", at: "2026-07-28T10:00:00Z", handle: "someone@example.com" });
  assert.equal(bad.ok, false);
  assert.match(bad.problems.join(" "), /identity never enters this path/i);
  const badDomain = normalizeEvent({ kind: "sent", at: "2026-07-28T10:00:00Z", handle: "acme.ca" });
  assert.equal(badDomain.ok, false);

  const text = readFileSync(new URL(`../${SRC}`, import.meta.url), "utf8")
    + readFileSync(new URL(RECORD, import.meta.url), "utf8");
  assert.equal(/[\w.-]+@[\w-]+\.[a-z]{2,}/i.test(text), false, "no email address appears in the module or the record");
});

test("U1: an undated or unknown-kind event is refused by name, never silently counted", () => {
  const undated = normalizeEvent({ kind: "sent", handle: "OB-S001" });
  assert.equal(undated.ok, false);
  assert.match(undated.problems.join(" "), /undated mail event is not evidence/i);
  const unknown = normalizeEvent({ kind: "lead", at: "2026-07-28T10:00:00Z", handle: "OB-S001" });
  assert.equal(unknown.ok, false);
  assert.match(unknown.problems.join(" "), /refused rather than counted as something else/i);

  const t = buildOutboundTruth({ source: "mail", events: [{ kind: "lead", at: "2026-07-28T10:00:00Z", handle: "X" }] }, { now: NOW });
  assert.equal(t.accepted, 0);
  assert.equal(t.rejected.length, 1);
  assert.equal(outboundFacts(t).emailsSent, NEVER);
});

test("U1: software progress cannot move a single number", () => {
  const base = { source: "mail", events: [{ kind: "sent", at: "2026-07-28T10:00:00Z", handle: "OB-S001" }] };
  const before = outboundFacts(buildOutboundTruth(base, { now: NOW }));
  const after = outboundFacts(buildOutboundTruth({
    ...base,
    sequencesCompleted: 21, tasksMerged: 3, testsGreen: 999, commits: 40, merges: 12, suiteGreen: true,
  }, { now: NOW }));
  assert.deepEqual(before, after, "sequences, suites, commits and merges are not inputs and cannot move outbound truth");
});

test("U2: reconciliation names an understated counter as a Rule 14 failure", () => {
  const t = buildOutboundTruth(realRecord(), { now: NOW });
  const r = reconcileWithClaimed(t, { asksSent: 0, meetingsBooked: 0 });
  assert.equal(r.clean, false);
  const asks = r.findings.find((f) => f.counter === "asksSent");
  assert.ok(asks, "the 0-vs-41 gap is found");
  assert.equal(asks.severity, "understated");
  assert.equal(asks.real, 41);
  assert.match(asks.statement, /same class as overstating/i);
  assert.equal(r.findings.find((f) => f.counter === "meetingsBooked"), undefined, "a true zero raises nothing");
});

test("U2: an unsourced counter is reported unverifiable, not clean", () => {
  const t = buildOutboundTruth({ events: [] }, { now: NOW });
  const r = reconcileWithClaimed(t, { asksSent: 0 });
  assert.equal(r.clean, false);
  assert.equal(r.findings[0].severity, "unverifiable");
});

test("U1: the module is pure - no fs, net, spawn, env, transport or persistence", () => {
  assert.equal(SENDS, false);
  assert.equal(HAS_TRANSPORT, false);
  assert.equal(PERSISTS, false);
  assert.equal(READS_IDENTITY, false);
  const src = readFileSync(new URL(`../${SRC}`, import.meta.url), "utf8");
  for (const banned of [
    /\bfrom\s+["']node:fs["']/, /\bfrom\s+["']node:child_process["']/, /\bfrom\s+["']node:net["']/,
    /\bfrom\s+["']node:https?["']/, /\bprocess\.env\b/, /\bfetch\s*\(/, /\bwriteFileSync\b/,
    /\bnodemailer\b/, /\bsendMail\b/, /\bsmtp\b/i,
  ]) {
    assert.equal(banned.test(src), false, `banned in a pure counter module: ${banned}`);
  }
  assert.ok(EVENT_KINDS.includes("sent") && EVENT_KINDS.includes("revenue"));
});
